Document: lamp-icon
Title: Debian lamp-icon Manual
Author: <insert document author here>
Abstract: This manual describes what lamp-icon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lamp-icon/lamp-icon.sgml.gz

Format: postscript
Files: /usr/share/doc/lamp-icon/lamp-icon.ps.gz

Format: text
Files: /usr/share/doc/lamp-icon/lamp-icon.text.gz

Format: HTML
Index: /usr/share/doc/lamp-icon/html/index.html
Files: /usr/share/doc/lamp-icon/html/*.html
